title: 'Institut National de l''Incongru'
baseline: 'INI'
baseurl: 'https://institut.incongru.org'
description: 'Site description.'
author:
    name: 'Constructions Incongrues'
    url: 'https://www.constructions-incongrues.net'
image: cecil-card.png
